builds/twolip.json, changelogs/twolip/PixelExtended_twolip-10.0-20200922-1718-OFFICIAL.zip.txt
Signed-off-by: niteshkumar2000 <nitesh156200@gmail.com>
=> tulip: Update 22 sept

xda_thread.txt
=> Fixed my stupid spelling error

support/maintainer.md
Yuppieeeee I totally forgot about this :dancing_men:
=> Mantainer for Poco X3

builds/jasmine_sprout.json, changelogs/jasmine_sprout/PixelExtended_jasmine_sprout-11.0-20210217-1019-OFFICIAL.zip.txt
=> OTA: Initial ota for jasmine_sprout

support/maintainer.md
Correction for poco x2 maintainer name.
=> Update for poco X2

changelogs/olivewood/PixelExtended_olivewood-11.0-20210518-0308-OFFICIAL.zip.txt, support/maintainer.md
sir add me in maintainers list
=> Update maintainers list

builds/enchilada.json, builds/fajita.json, changelogs/enchilada/PixelExtended_enchilada-11.0-20210619-1057-OFFICIAL.zip.txt, changelogs/fajita/PixelExtended_fajita-11.0-20210620-1829-OFFICIAL.zip.txt
Signed-off-by: zahidmgsk <zahidmgsk@gmail.com>
=> Enchilada / Fajita: 21st June 2021 Release

builds/avicii.json, changelogs/avicii/PixelExtended_avicii-11.0-20210623-0938-OFFICIAL.zip.txt, support/maintainer.md
Signed-off-by: manikantaraavi <raavimanikanta6595@gmail.com>
=> avicii: 06/23/2021 Update

builds/avicii.json, changelogs/avicii/PixelExtended_avicii-11.0-20210717-1315-OFFICIAL.zip.txt
Signed-off-by: manikantaraavi <raavimaniaknta6595@gmail.com>
=> avicii: July update

builds/RMX2001.json, changelogs/RMX2001/PixelExtended_RMX2001-11.0-20210722-0404-OFFICIAL.zip.txt
Change-Id: I7b9a8c3f79005283747bf72473b02c620f796540
=> RMX2001 : July update

builds/kebab.json, changelogs/kebab/PixelExtended_kebab-11.0-20210816-0806-OFFICIAL.zip.txt
Signed-off-by: rounak1619 <rounakmehata9@gmail.com>
=> kebab: August update

builds/juice.json, changelogs/juice/PixelExtended_juice-11.0-20210906-0217-OFFICIAL.zip.txt
=> juice: v3.1 update

builds/RMX2001.json, changelogs/RMX2001/PixelExtended_RMX2001-11.0-20210911-1317-OFFICIAL.zip.txt
Change-Id: I545113637b23b37fff5d53a5b8f72b86144bbd5c
=> RMX2001 : September update

builds/juice.json, changelogs/juice/PixelExtended_juice-11.0-20210917-1223-OFFICIAL.zip.txt
=> juice: v3.2 update

builds/olivewood.json, changelogs/olivewood/PixelExtended_olivewood-11.0-20210918-0235-OFFICIAL.zip.txt
Signed-off-by: shield44 <motoecondorxt1022@gmail.com>
=> OTA: olivewood: sept pex 3.2 update

builds/lavender.json, changelogs/lavender/PixelExtended_lavender-11.0-20210918-0757-OFFICIAL.zip.txt
Signed-off-by: Prashant-1695 <prashant33968@gmail.com>
=> lavender: v3.2 update

support/maintainer.md
=> add sweet official

builds/sweet.json, changelogs/sweet/PixelExtended_sweet-11.0-20210920-0942-OFFICIAL.zip.txt
=> Update 3.2 sweet

builds/lemonkebab.json, changelogs/lemonkebab/PixelExtended_lemonkebab-11.0-20211117-0915-OFFICIAL.zip.txt
=> LemonKebab:VERTEX

builds/avicii.json, changelogs/avicii/PixelExtended_avicii-11.0-20211120-0845-OFFICIAL.zip.txt
=> avicii:VERTEX

builds/sweet.json, changelogs/sweet/PixelExtended_sweet-11.0-20211121-0947-OFFICIAL.zip.txt
=> update eol sweet

builds/juice.json, changelogs/juice/PixelExtended_juice-11.0-20211202-1900-OFFICIAL.zip.txt
=> juice:VERTEX

builds/sweet.json, changelogs/sweet/PixelExtended_sweet-12.0-20211218-1649-OFFICIAL.zip.txt
=> Sweet official build

builds/RMX1971.json, changelogs/RMX1971/PixelExtended_RMX1971-12.0-20211219-0055-OFFICIAL.zip.txt
Accept PR for PEX 4.0 Official Release
=> RMX1971 Official

builds/bonito.json, changelogs/bonito/PixelExtended_bonito-12.0-20211220-2341-OFFICIAL.zip.txt
Please attach this boot.img link to the post, this device needs it
https://sourceforge.net/projects/pixelextended/files/bonito/PixelExtended_bonito-12.0-20211220-2341-OFFICIAL.img/download
=> OTA : Bonito 4.0

builds/lemonkebab.json, changelogs/lemonkebab/PixelExtended_lemonkebab-12.0-20211223-0220-OFFICIAL.zip.txt
=> Lemonkebab 4.0

builds/avicii.json, changelogs/avicii/PixelExtended_avicii-12.0-20220102-0819-OFFICIAL.zip.txt
=> avicii: 4.0

builds/alioth.json, changelogs/alioth/PixelExtended_alioth-12.0-20220115-0930-OFFICIAL.zip.txt
Signed-off-by: Rounak1619 <rounakmehata9@gmail.com>
=> Alioth : 4.0

builds/juice.json, changelogs/juice/PixelExtended_juice-12.0-20220125-1827-OFFICIAL.zip.txt
=> juice: v4.1 update

builds/lavender.json, changelogs/lavender/PixelExtended_lavender-12.0-20220126-1757-OFFICIAL.zip.txt
Signed-off-by: ImPrashantt <prashant33968@gmail.com>
=> lavender v4.1 Update

builds/sweet.json, changelogs/sweet/PixelExtended_sweet-12.0-20220126-1244-OFFICIAL.zip.txt
=> sweet V4.1 Update

builds/lemonkebab.json, changelogs/lemonkebab/PixelExtended_lemonkebab-12.0-20220127-0701-OFFICIAL.zip.txt
=> lemonkebab : 4.1

builds/avicii.json, changelogs/avicii/PixelExtended_avicii-12.0-20220128-1323-OFFICIAL.zip.txt
=> avicii: 4.1

builds/avicii.json, changelogs/avicii/PixelExtended_avicii-12.0-20220227-0518-OFFICIAL.zip.txt
=> avicii : I didn't forget

builds/juice.json, changelogs/juice/PixelExtended_juice-12.0-20220305-1839-OFFICIAL.zip.txt
=> juice: v4.2 update

builds/sweet.json, changelogs/sweet/PixelExtended_sweet-12.0-20220306-1848-OFFICIAL.zip.txt
=> sweet: v4.2 update

builds/sweet.json, changelogs/sweet/PixelExtended_sweet-12.1-20220409-1404-OFFICIAL.zip.txt
=> sweet: 4.3 update

builds/juice.json, changelogs/juice/PixelExtended_juice-12.1-20220501-0731-OFFICIAL.zip.txt
=> juice: v4.4 update

builds/sweet.json, changelogs/sweet/PixelExtended_sweet-12.1-20220501-1622-OFFICIAL.zip.txt
=> sweet: v4.4 update

builds/onclite.json, changelogs/onclite/PixelExtended_onclite-12.1-20220505-1522-OFFICIAL.zip.txt
=> onclite: v4.4 OTA and Changelog

builds/onclite.json, changelogs/onclite/PixelExtended_onclite-12.1-20220519-0904-OFFICIAL.zip.txt
=> onclite: v4.5 OTA and Changelog

builds/avicii.json, changelogs/avicii/PixelExtended_avicii-12.1-20220614-0601-OFFICIAL.zip.txt
Signed-off-by: manikantaraavi <raavimanikanta6595@gmail.com>
=> avicii : 4.6

builds/avicii.json, changelogs/avicii/PixelExtended_avicii-12.1-20220616-0710-OFFICIAL.zip.txt
Signed-off-by: manikantaraavi <raavimanikanta6595@gmail.com>
=> avicii: HotFix

builds/juice.json, changelogs/juice/PixelExtended_juice-12.1-20220701-1219-OFFICIAL.zip.txt
=> juice: v4.6 update

builds/avicii.json, changelogs/avicii/PixelExtended_avicii-12.1-20220720-1442-OFFICIAL.zip.txt
Signed-off-by: manikantaraavi <raavimanikanta6595@gmail.com>
=> avicii: 4.7

builds/lavender.json, changelogs/lavender/PixelExtended_lavender-12.1-20220718-0505-OFFICIAL.zip.txt
Signed-off-by: moonitime <moonitimeultraromantic@gmail.com>
=> lavender: v4.7 Update

builds/juice.json, changelogs/juice/PixelExtended_chime-12.1-20220727-1613-OFFICIAL.zip.txt
=> chime: v4.7 update

changelogs/juice/PixelExtended_chime-12.1-20220727-1613-OFFICIAL.zip.txt
=> chime: update v4.7 changelogs

builds/lavender.json, changelogs/lavender/PixelExtended_lavender-12.1-20220812-2240-OFFICIAL.zip.txt
Signed-off-by: Moonitime: The Yandere <moonitimetheyandere@gmail.com>
=> lavender: V4.8

builds/onclite.json, changelogs/onclite/PixelExtended-4.8-onclite-12.1-20220814-1334-OFFICIAL.zip.txt
=> onclite: v4.8 OTA & Changelogs

builds/beyond0lte.json, changelogs/beyond0lte/PixelExtended-5.0_beyond0lte-13.0-20221004-0807-OFFICIAL.zip.txt
=> beyond0lte: V5.0

builds/beyond1lte.json, changelogs/beyond1lte/PixelExtended-5.0_beyond1lte-13.0-20221004-0907-OFFICIAL.zip.txt
=> beyond1lte: V5.0

builds/beyond2lte.json, changelogs/beyond2lte/PixelExtended-5.0_beyond2lte-13.0-20221004-0928-OFFICIAL.zip.txt
=> beyond2lte: V5.0

builds/beyondx.json, changelogs/beyondx/PixelExtended-5.0_beyondx-13.0-20221004-0958-OFFICIAL.zip.txt
=> beyondx: V5.0

builds/lavender.json, changelogs/lavender/PixelExtended-5.0_lavender-13.0-20221005-1737-OFFICIAL.zip.txt
Signed-off-by: Shizuka Hinode <moonitimetheyandere@gmail.com>
=> lavender: V5.0

builds/sweet.json, changelogs/sweet/PixelExtended-5.0_sweet-13.0-20221006-2140-OFFICIAL.zip.txt
Signed-off-by: Sought <brolhotorto@gmail.com>
=> sweet: Initial V5.0 release

builds/onclite.json, changelogs/onclite/PixelExtended-5.0_onclite-13.0-20221011-1032-OFFICIAL.zip.txt
=> onclite: v5.0 OTA & Changelogs

builds/sweet.json, changelogs/sweet/PixelExtended-5.2_sweet-13.0-20221127-1245-OFFICIAL.zip.txt
=> sweet: v5.2 OTA & Changelogs

builds/beyond0lte.json, changelogs/beyond0lte/PixelExtended-5.4_beyond0lte-13.0-20230114-1815-OFFICIAL.zip.txt
=> beyond0lte: V5.4

builds/beyond1lte.json, changelogs/beyond1lte/PixelExtended-5.4_beyond1lte-13.0-20230114-1722-OFFICIAL.zip.txt
=> beyond1lte: V5.4

builds/beyond2lte.json, changelogs/beyond2lte/PixelExtended-5.4_beyond2lte-13.0-20230114-1747-OFFICIAL.zip.txt
=> beyond2lte: V5.4

builds/beyondx.json, changelogs/beyondx/PixelExtended-5.4_beyondx-13.0-20230114-1948-OFFICIAL.zip.txt
=> beyondx: V5.4

builds/sweet.json, changelogs/sweet/PixelExtended-5.4_sweet-13.0-20230127-1133-OFFICIAL.zip.txt
=> sweet: v5.4 OTA & Changelogs
